# Generated by Django 2.1.2 on 2018-10-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='date',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='transfers',
            old_name='date',
            new_name='timestamp',
        ),
        migrations.AlterField(
            model_name='transfers',
            name='transfer_type',
            field=models.CharField(blank=True, choices=[('CRT', 'Credit'), ('DBT', 'Debit')], max_length=3),
        ),
    ]
